application: www-gwax
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# Dynamic handlers
- url: /\.well-known/.*
  script: letsencrypt_handler.app

- url: /dynamictest
  script: gwax_flask.app

# Static handlers
- url: /(.+\.(html|js|css)$)
  static_files: static/\1
  upload: static//(.+\.(html|js|css)$)
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+\.[A-Za-z0-9]+$)
  static_files: static/\1
  upload: static/(.+\.[A-Za-z0-9]+$)
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.
