application: www-gwax
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
#- url: /dynamictest
#  script: gwax_flask.app

# Let's Encrypt handlers
- url: /\.well-known/acme-challenge/(.+)
  static_files: well-known/\1
  upload: well-known/(.+)
  mime_type: text/plain

# Static site handlers
- url: /(.+\.(html|js|css)$)
  static_files: static/\1
  upload: static/(.+\.(html|js|css)$)
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+\.md$)
  static_files: static/\1
  upload: static/(.+\.md$)
  mime_type: text/x-markdown
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+\.rst$)
  static_files: static/\1
  upload: static/(.+\.rst$)
  mime_type: text/x-rst
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+\.[A-Za-z0-9]+$)
  static_files: static/\1
  upload: static/(.+\.[A-Za-z0-9]+$)
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.

- url: /
  static_files: static/index.html
  upload: static/index.html
  http_headers:
    X-Narwhal: A small arctic whale. The male has a long tusk.
